name: Build Artifact
on:
  push:
    branches: [master]
    paths-ignore:
      - "**.md"
      - ".github/**"
      - "assets/**"
  pull_request:
    branches: [master]
  workflow_call:
    outputs:
      version:
        description: "Version builded"
        value: ${{ jobs.build.outputs.version }}
jobs:
  build:
    name: Build
    strategy:
      matrix:
        configuration: [Release]
        profile: [win, win-472]
        include:
          - profile: "win"
            framework: "net6.0-windows"
          - profile: "win-472"
            framework: "net472"
    runs-on: windows-latest
    env:
      DOTNET_NOLOGO: true
      SolutionName: RRTools.sln
      Configuration: ${{ matrix.configuration }}
      Profile: ${{ matrix.profile }}
      Framework: ${{ matrix.framework }}
    outputs:
      version: ${{steps.version.outputs.version}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.x

      - name: Set VERSION
        id: version
        run: .\.github\scripts\version.ps1

      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: ~\.nuget\packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Build solution
        run: |
          dotnet restore --locked-mode
          dotnet build -c $env:Configuration

      - name: Build artifact
        if: matrix.configuration == 'Release'
        run: dotnet publish -c Release -p:PublishProfile=$env:Profile -f $env:Framework /property:Version=$env:VERSION

      - name: Upload artifact
        if: matrix.configuration == 'Release'
        uses: actions/upload-artifact@v3
        with:
          name: RRTools(${{ matrix.profile }})
          path: RR.WinForms\publish\${{ matrix.profile }}\**
          if-no-files-found: error
