name: Publish Artifact
on:
  workflow_dispatch:
jobs:
  build:
    name: Build
    uses: ./.github/workflows/build-artifact.yml

  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: build
    steps:
      - name: Version
        run: echo "Version builded ${{ needs.build.outputs.version }}"

      - name: Download artifacts
        uses: actions/download-artifact@v3

      - name: List files
        run: ls -R

      - name: Archive artifacts
        run: |
          zip -r "RRTools.NET-6.0.zip" "RRTools(net6.0-windows)"
          zip -r "RRTools.NET-4.7.2.zip" "RRTools(net472)"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            RRTools.NET-6.0.zip
            RRTools.NET-4.7.2.zip
