name: Publish Artifact
on:
  workflow_dispatch:
jobs:
  build:
    name: Build
    uses: ./.github/workflows/build-artifact.yml

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Version
        run: echo "Version builded ${{ needs.build.outputs.version }}"

      - name: Download artifacts
        uses: actions/download-artifact@v3

      - name: List files
        run: ls -R

      - name: Archive artifacts
        run: |
          zip -r "RRTools(NET.6).zip" "RRTools(win)"
          zip -r "RRTools(NET.472).zip" "RRTools(win-472)"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            RRTools.zip
            RRTools(dotnet).zip
